### PR TITLE
implement add_series() endpoint in sonarr-api-wrapper

### PR DESCRIPTION
**Pull request by bnorquist**
I also removed python2 specification from the readme as it works fine in python 3 too :)

### CODE REVIEW

**Comment by SLiX69** [comment]
Hi, thanks for the PR. Did you test this? I don't have the time right now to do that :(

regards

**Comment by bnorquist** [comment]
Yes I did. It worked for a few different shows on my sonarr setup. Essentially if you pass add_series() a valid tvdbId it will add a show successfully. I wanted to get this endpoint working so I can use it in a sonarr slackbot project i'm working on :)

Thanks for your hard work in setting up this wrapper!

**Comment by bnorquist** [comment]
The only thing I will note is that I hardcoded in the qualityprofile as '4' (1080p). I couldn't figure out the quality profiles response from get_quality_profiles() works. There seemed to be multiple id numbers for each quality. If I figure it out i'm happy to commit a better solution that makes the quality configurable in add_series().

**Comment by bnorquist** [comment]
bump @SLiX69

**Comment by SLiX69** [comment]
Hi, sorry for the very late reply. Totally forgot about this PR. 

I'm not sure, if this is a feature, which should be implemented in the wrapper itself.
btw I don't like the '1080p' hardcode :D 
Maybe in two weeks I'll have some time to look into this. Sorry about my bad response time

**Comment by bnorquist** [comment]
@SLiX69 No worries, sure you are busy! Yeah I don't like that part either. I think if we can figure out the quality thing it is worth adding the add_series() method. It opens up some really cool functionality. I have included the response from get_quality_profiles() on my Sonarr setup below. I really can't figure out the relationship between 'id' and the actual quality.

[
   {
      "cutoff": {
         "id": 1,
         "name": "SDTV"
      },
      "id": 1,
      "items": [
         {
            "allowed": false,
            "quality": {
               "id": 0,
               "name": "Unknown"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 1,
               "name": "SDTV"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 8,
               "name": "WEBDL-480p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 2,
               "name": "DVD"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 4,
               "name": "HDTV-720p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 9,
               "name": "HDTV-1080p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 10,
               "name": "Raw-HD"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 5,
               "name": "WEBDL-720p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 6,
               "name": "Bluray-720p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 3,
               "name": "WEBDL-1080p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 7,
               "name": "Bluray-1080p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 16,
               "name": "HDTV-2160p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 18,
               "name": "WEBDL-2160p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 19,
               "name": "Bluray-2160p"
            }
         }
      ],
      "language": "english",
      "name": "Any"
   },
   {
      "cutoff": {
         "id": 1,
         "name": "SDTV"
      },
      "id": 2,
      "items": [
         {
            "allowed": false,
            "quality": {
               "id": 0,
               "name": "Unknown"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 1,
               "name": "SDTV"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 8,
               "name": "WEBDL-480p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 2,
               "name": "DVD"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 4,
               "name": "HDTV-720p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 9,
               "name": "HDTV-1080p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 10,
               "name": "Raw-HD"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 5,
               "name": "WEBDL-720p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 6,
               "name": "Bluray-720p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 3,
               "name": "WEBDL-1080p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 7,
               "name": "Bluray-1080p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 16,
               "name": "HDTV-2160p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 18,
               "name": "WEBDL-2160p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 19,
               "name": "Bluray-2160p"
            }
         }
      ],
      "language": "english",
      "name": "SD"
   },
   {
      "cutoff": {
         "id": 4,
         "name": "HDTV-720p"
      },
      "id": 3,
      "items": [
         {
            "allowed": false,
            "quality": {
               "id": 0,
               "name": "Unknown"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 1,
               "name": "SDTV"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 8,
               "name": "WEBDL-480p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 2,
               "name": "DVD"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 4,
               "name": "HDTV-720p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 9,
               "name": "HDTV-1080p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 10,
               "name": "Raw-HD"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 5,
               "name": "WEBDL-720p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 6,
               "name": "Bluray-720p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 3,
               "name": "WEBDL-1080p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 7,
               "name": "Bluray-1080p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 16,
               "name": "HDTV-2160p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 18,
               "name": "WEBDL-2160p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 19,
               "name": "Bluray-2160p"
            }
         }
      ],
      "language": "english",
      "name": "HD-720p"
   },
   {
      "cutoff": {
         "id": 9,
         "name": "HDTV-1080p"
      },
      "id": 4,
      "items": [
         {
            "allowed": false,
            "quality": {
               "id": 0,
               "name": "Unknown"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 1,
               "name": "SDTV"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 8,
               "name": "WEBDL-480p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 2,
               "name": "DVD"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 4,
               "name": "HDTV-720p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 9,
               "name": "HDTV-1080p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 10,
               "name": "Raw-HD"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 5,
               "name": "WEBDL-720p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 6,
               "name": "Bluray-720p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 3,
               "name": "WEBDL-1080p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 7,
               "name": "Bluray-1080p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 16,
               "name": "HDTV-2160p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 18,
               "name": "WEBDL-2160p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 19,
               "name": "Bluray-2160p"
            }
         }
      ],
      "language": "english",
      "name": "HD-1080p"
   },
   {
      "cutoff": {
         "id": 16,
         "name": "HDTV-2160p"
      },
      "id": 5,
      "items": [
         {
            "allowed": false,
            "quality": {
               "id": 0,
               "name": "Unknown"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 1,
               "name": "SDTV"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 8,
               "name": "WEBDL-480p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 2,
               "name": "DVD"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 4,
               "name": "HDTV-720p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 9,
               "name": "HDTV-1080p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 10,
               "name": "Raw-HD"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 5,
               "name": "WEBDL-720p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 6,
               "name": "Bluray-720p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 3,
               "name": "WEBDL-1080p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 7,
               "name": "Bluray-1080p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 16,
               "name": "HDTV-2160p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 18,
               "name": "WEBDL-2160p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 19,
               "name": "Bluray-2160p"
            }
         }
      ],
      "language": "english",
      "name": "Ultra-HD"
   },
   {
      "cutoff": {
         "id": 4,
         "name": "HDTV-720p"
      },
      "id": 6,
      "items": [
         {
            "allowed": false,
            "quality": {
               "id": 0,
               "name": "Unknown"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 1,
               "name": "SDTV"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 8,
               "name": "WEBDL-480p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 2,
               "name": "DVD"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 4,
               "name": "HDTV-720p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 9,
               "name": "HDTV-1080p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 10,
               "name": "Raw-HD"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 5,
               "name": "WEBDL-720p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 6,
               "name": "Bluray-720p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 3,
               "name": "WEBDL-1080p"
            }
         },
         {
            "allowed": true,
            "quality": {
               "id": 7,
               "name": "Bluray-1080p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 16,
               "name": "HDTV-2160p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 18,
               "name": "WEBDL-2160p"
            }
         },
         {
            "allowed": false,
            "quality": {
               "id": 19,
               "name": "Bluray-2160p"
            }
         }
      ],
      "language": "english",
      "name": "HD - 720p/1080p"
   }
]

**Comment by SLiX69** [comment]
Hi, I see, you've got many quality profiles. I only set up one profile, deleted the others, so this was not a problem to me, iirc. Will look into this, maybe this weekend

**Comment by bnorquist** [comment]
Cool thanks. I only set up two quality profiles so I'm not sure why there are so many. Most of them have "allowed": false not sure what is causing that.

**Comment by SLiX69** [comment]
Hi, just took a look at your JSON response:

Looks like you've set up 6 profiles, "Any", "SD", "HD-720p", "HD-1080p", "Ultra-HD", "HD - 720p/1080p".
There are so many objects, cause every profile got a array called "items", which holds the wanted qualities for this specific profile ("SDTV", "DVD", ...). But the actual profiles array just contains of 6 objects/profiles (id's 1-6).

Try to format your json data or use a tool, which makes your response browseable, then you'll notice it

**Comment by bnorquist** [comment]
Thanks @ SLiX69 ! I'll take a deeper look at that json with your tips and make the PR non-harcoded for quality profile once I fully understand it.

**Comment by bnorquist** [comment]
@SLiX69 Ok, I figured out a much easier workaround. Just pass quality profile id as a parameter to add show. get_quality_profiles() gives a json where an outside program can determine which id to pass. I think this should be good to merge now if you are cool with it.

**Comment by SLiX69** [comment]
Hi, my intention of 'add_series' was, that everything you do in 'get_series_to_add' is done 'outside' of 'add_series' and just pass this as parameter(data) to the function. 
Imagine a UI, which uses this wrapper and at first asks for show name, then lists quality profile so you can choose one, monitoring or season-folder-creation option, .. Upon the gathered information, the json data will be build and then only passed to 'add_series'.

This does not work anymore, do you see what I mean?

**Comment by bnorquist** [comment]
Yeah that makes sense.

Let me see if I can re-work it that way. Thanks for the feedback, haven't
written a wrapper before so this is a good learning opportunity.

**Comment by bnorquist** [comment]
@SLiX69 How does this look? I put add_series back to its original form but kept get_series_to_add(). I think it adds a nice functionality to be able to construct a valid json to add a series from just a tvdbid and a quality profile id. It can also serve as an example for json to be passed to add_series() from some app method outside of this wrapper.

**Comment by SLiX69** [comment]
sorry again to keep you waiting. I'll look into this the next days.
I agree with you, good to have an example, or the additional get_series_to_add().

**Comment by SLiX69** [comment]
Thanks for your patience, time and effort, will merge this now!

**Comment by bnorquist** [comment]
Thanks for your guidance along the way!

**Pull request merged**
